Repository fosslight/fosslight_binary_scanner, pull requests merged in 2022-06, with the labels that each got.

#54 Add yaml format for FOSSLight Report
  .github/workflows/pull-request.yml
  src/fosslight_binary/_help.py
  src/fosslight_binary/binary_analysis.py
Labels: enhancement, chore

#55 Let the binary filter be used externally
  src/fosslight_binary/binary_analysis.py
Labels: chore

#56 Fix a bug where the current ar archive file is not considered binary.
  src/fosslight_binary/binary_analysis.py
Labels: bug fix

#57 update the minimum version of fosslight_util
  requirements.txt
Labels: chore

#58 Fix memory bug when checking file type on windows
  src/fosslight_binary/binary_analysis.py
Labels: bug fix
