Repository fosslight/fosslight_binary_scanner, pull requests merged in 2022-02, with the labels that each got.

#35 Fix to make executable file with latest version
  .github/workflows/publish-release.yml
Labels: bug fix

#36 Return a list of successes and results
  src/fosslight_binary/binary_analysis.py
Labels: chore

#37 Modify to print output file name
  requirements.txt
  src/fosslight_binary/_jar_analysis.py
  src/fosslight_binary/binary_analysis.py
Labels: chore

#39 Change the log level related to the output file
  src/fosslight_binary/binary_analysis.py
Labels: chore

#43 Fix to make executable file including 'dependency-check' package
  src/fosslight_binary/_jar_analysis.py
Labels: bug fix

#44 Set CVE valid time to 24 hours
  src/fosslight_binary/_jar_analysis.py
Labels: chore

#46 Modify LicenseRef-3rd_party_licenses.txt
  LICENSES/LicenseRef-3rd_party_licenses.txt
Labels: documentation

#45 Add error handle for dependency-check running
  src/fosslight_binary/_jar_analysis.py
  src/fosslight_binary/binary_analysis.py
Labels: chore
