Repository fosslight/fosslight_binary_scanner, pull requests merged in 2022-01, with the labels that each got.

#22 Apply OWASP dependency-check to analyze jar file
  requirements.txt
  src/fosslight_binary/_binary.py
  src/fosslight_binary/_binary_dao.py
  src/fosslight_binary/_jar_analysis.py
  src/fosslight_binary/binary_analysis.py
  tests/error_prone_annotations-2.7.1.jar
  tox.ini
Labels: enhancement

#24 Apply OWASP dependency-check to analyze jar file
  .reuse/dep5
  requirements.txt
  src/fosslight_binary/_binary.py
  src/fosslight_binary/_binary_dao.py
  src/fosslight_binary/_help.py
  src/fosslight_binary/_jar_analysis.py
  src/fosslight_binary/binary_analysis.py
  tests/error_prone_annotations-2.7.1.jar
  tox.ini
Labels: enhancement

#25 Fix the bug where there is no start time
  .github/workflows/pull-request.yml
  src/fosslight_binary/binary_analysis.py
Labels: bug fix

#26 Remove remained code related to -a option
  src/fosslight_binary/_help.py
  src/fosslight_binary/binary_analysis.py
  tox.ini
Labels: chore

#27 Print the extension to the output file of the result log
  src/fosslight_binary/binary_analysis.py
Labels: bug fix

#29 Do not print comment if there is no information from OWASP
  src/fosslight_binary/_jar_analysis.py
  src/fosslight_binary/binary_analysis.py
Labels: bug fix

#30 Add vulnerability column for jar file analysis result
  requirements.txt
  src/fosslight_binary/_binary.py
  src/fosslight_binary/_jar_analysis.py
  src/fosslight_binary/binary_analysis.py
Labels: enhancement

#33 Fix to local variable assignment issue - extended header
  src/fosslight_binary/binary_analysis.py
Labels: bug fix
