Repository fosslight/fosslight_binary_scanner, pull requests merged in 2024-10, with the labels that each got.

#126 Support spdx
  requirements.txt
  src/fosslight_binary/_binary.py
  src/fosslight_binary/binary_analysis.py
  src/fosslight_binary/cli.py
Labels: enhancement, minor

#130 Apply simple mode
  src/fosslight_binary/_simple_mode.py
  src/fosslight_binary/binary_analysis.py
  src/fosslight_binary/cli.py
Labels: enhancement

#131 Print option name with error msg
  src/fosslight_binary/binary_analysis.py
Labels: chore
